/**
 * Gera CSS variables a partir dos tokens compartilhados de @kinevo/shared/tokens.
 *
 * Estratégia (Fase 0): segue a "Shield Strategy" do web — NÃO sobrescreve nenhuma
 * var existente em globals.css. Em vez disso, expõe novas vars `--k-*` (prefixo
 * Kinevo) que componentes futuros (Fase 1+) podem consumir sem regressão visual
 * em código existente.
 *
 * Source of truth: shared/tokens/v2/* (paleta Kinevo Premium DS v2).
 */
import * as tokens from '@kinevo/shared/tokens';

type ColorScale = Record<string | number, string>;

function emitScale(prefix: string, scale: ColorScale): string {
  return Object.entries(scale)
    .map(([key, value]) => `  --${prefix}-${key}: ${value};`)
    .join('\n');
}

export function generateThemeCss(): string {
  const v2 = tokens.v2;
  const lines: string[] = [];

  lines.push('/* AUTO-GENERATED by web/scripts/sync-tokens.mjs — do not edit by hand. */');
  lines.push('/* Source: @kinevo/shared/tokens (v2). Adds Kinevo `--k-*` vars without */');
  lines.push('/* overriding any existing var (Shield Strategy preserved).            */');
  lines.push('');
  lines.push(':root {');
  lines.push('  /* Brand purple scale (Kinevo Premium DS v2) */');
  lines.push(emitScale('k-purple', v2.colors.purple));
  lines.push('');
  lines.push('  /* Neutral scale (Apple HIG-aligned) */');
  lines.push(emitScale('k-neutral', v2.colors.neutral));
  lines.push('');
  lines.push('  /* Semantic colors */');
  for (const name of ['success', 'warning', 'danger', 'info'] as const) {
    const group = v2.colors.semantic[name];
    lines.push(`  --k-${name}: ${group.default};`);
    lines.push(`  --k-${name}-bg: ${group.bg};`);
    lines.push(`  --k-${name}-fg: ${group.fg};`);
  }
  lines.push('');
  lines.push('  /* Surface tokens */');
  lines.push(`  --k-surface-canvas: ${v2.colors.surface.canvas};`);
  lines.push(`  --k-surface-card: ${v2.colors.surface.card};`);
  lines.push(`  --k-surface-card-2: ${v2.colors.surface.card2};`);
  lines.push(`  --k-surface-tint-purple: ${v2.colors.surface.tintPurple};`);
  lines.push(`  --k-surface-glass: ${v2.colors.surface.glass};`);
  lines.push('');
  lines.push('  /* Radius scale */');
  for (const [key, value] of Object.entries(v2.radius)) {
    lines.push(`  --k-radius-${key}: ${value}px;`);
  }
  lines.push('');
  lines.push('  /* Shadow scale (web string) */');
  for (const [key, value] of Object.entries(v2.shadows)) {
    const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`  --k-shadow-${cssKey}: ${(value as { web: string }).web};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}
