/**
 * Gera web/src/app/_tokens.generated.css a partir de @kinevo/shared/tokens.
 * Usage: cd web && node scripts/sync-tokens.mjs
 *
 * Roda em CI (prebuild) e em dev quando tokens mudam. Saída é committed.
 * Implementação Node puro (sem ts-node / tsx) — duplica a lógica de
 * tokens-to-css.ts para evitar dependência de runtime TS no build.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const sharedRoot = resolve(__dirname, '..', '..', 'shared', 'tokens');
const outPath = resolve(__dirname, '..', 'src', 'app', '_tokens.generated.css');

// Carrega tokens do shared via dynamic import (TS files via ESM loader não funcionam
// em Node puro — então repetimos os valores aqui, mantidos em sync via snapshot test
// no shared/tokens/__tests__).
//
// Para evitar duplicação real, lemos os arquivos como texto e extraímos os literais
// usando uma evaluação manual segura (eval-less).
import { readFileSync } from 'node:fs';

function loadV2Module(name) {
  const src = readFileSync(resolve(sharedRoot, 'v2', `${name}.ts`), 'utf8');
  // Strip TS types/exports e isola o objeto principal. Estratégia simples: pega o
  // primeiro `export const <name> = { ... } as const;` e converte pra JSON-like.
  // Os arquivos v2/* são literais 100% — não há runtime; um parser ad-hoc basta.
  return src;
}

function extractObject(src, identifier) {
  const re = new RegExp(`(?:export\\s+const|const)\\s+${identifier}\\s*(?::[^=]+)?=\\s*({[\\s\\S]*?})\\s*as\\s+const`);
  const m = src.match(re);
  if (!m) throw new Error(`Could not extract '${identifier}' from source`);
  // Converte literal TS pra JSON (chaves não-aspadas → aspadas, trailing commas, comentários).
  let body = m[1];
  body = body.replace(/\/\/[^\n]*/g, '');
  body = body.replace(/\/\*[\s\S]*?\*\//g, '');
  body = body.replace(/([{,]\s*)([A-Za-z_$][\w$]*|\d+)\s*:/g, '$1"$2":');
  body = body.replace(/,(\s*[}\]])/g, '$1');
  return JSON.parse(body);
}

const colorsSrc = loadV2Module('colors');
const radiusSrc = loadV2Module('radius');
const shadowsSrc = loadV2Module('shadows');

const purple = extractObject(colorsSrc, 'purple');
const neutral = extractObject(colorsSrc, 'neutral');
const semantic = extractObject(colorsSrc, 'semantic');
const surface = extractObject(colorsSrc, 'surface');
const radius = extractObject(radiusSrc, 'radius');

// Para shadows, queremos só o campo `web` de cada token. Parse mais cirúrgico:
function extractShadowsWeb(src) {
  // Captura cada token top-level (xs, sm, md, lg, glowPurple, glass) e seu campo `web`.
  // Match não-greedy entre o nome e o `web:`, com lookahead pra evitar capturar
  // `shadowOffset` aninhado.
  const re = /^\s{2}(xs|sm|md|lg|glowPurple|glass):\s*\{[\s\S]*?web:\s*"([^"]+)"/gm;
  const out = {};
  let m;
  while ((m = re.exec(src)) !== null) {
    out[m[1]] = m[2];
  }
  return out;
}
const shadowsWeb = extractShadowsWeb(shadowsSrc);

function emitScale(prefix, scale) {
  return Object.entries(scale)
    .map(([key, value]) => `  --${prefix}-${key}: ${value};`)
    .join('\n');
}

function generate() {
  const lines = [];
  lines.push('/* AUTO-GENERATED by web/scripts/sync-tokens.mjs — do not edit by hand. */');
  lines.push('/* Source: @kinevo/shared/tokens (v2). Adds Kinevo `--k-*` vars without */');
  lines.push('/* overriding any existing var (Shield Strategy preserved).            */');
  lines.push('');
  lines.push(':root {');
  lines.push('  /* Brand purple scale (Kinevo Premium DS v2) */');
  lines.push(emitScale('k-purple', purple));
  lines.push('');
  lines.push('  /* Neutral scale (Apple HIG-aligned) */');
  lines.push(emitScale('k-neutral', neutral));
  lines.push('');
  lines.push('  /* Semantic colors */');
  for (const name of ['success', 'warning', 'danger', 'info']) {
    const group = semantic[name];
    lines.push(`  --k-${name}: ${group.default};`);
    lines.push(`  --k-${name}-bg: ${group.bg};`);
    lines.push(`  --k-${name}-fg: ${group.fg};`);
  }
  lines.push('');
  lines.push('  /* Surface tokens */');
  lines.push(`  --k-surface-canvas: ${surface.canvas};`);
  lines.push(`  --k-surface-card: ${surface.card};`);
  lines.push(`  --k-surface-card-2: ${surface.card2};`);
  lines.push(`  --k-surface-tint-purple: ${surface.tintPurple};`);
  lines.push(`  --k-surface-glass: ${surface.glass};`);
  lines.push('');
  lines.push('  /* Radius scale */');
  for (const [key, value] of Object.entries(radius)) {
    lines.push(`  --k-radius-${key}: ${value}px;`);
  }
  lines.push('');
  lines.push('  /* Shadow scale (web) */');
  for (const [key, value] of Object.entries(shadowsWeb)) {
    const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`  --k-shadow-${cssKey}: ${value};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

const css = generate();
writeFileSync(outPath, css, 'utf8');
console.log(`✓ Wrote ${outPath} (${css.length} bytes)`);
