// ============================================================================
// Kinevo Prescription Engine v2 — Compact Output Schemas
// ============================================================================
// Defines the minimal JSON structures that LLMs return in the v2 pipeline.
// The LLM outputs ONLY IDs, numbers, and enum keys — no free-form text.
// Human-readable text is generated by output-enricher.ts on the backend.
//
// Two schemas:
//   1. CompactAnalysisOutput — returned by analysis model (Claude Haiku)
//   2. CompactGenerationOutput — returned by generation model (GPT-4.1-mini)

import type { ExerciseFunction } from '@kinevo/shared/types/prescription'

// ============================================================================
// Prompt version
// ============================================================================
// Bumped whenever the smart-v2 prompt structure or schema changes. Logged with
// every generation in prescription_generations.prompt_version for attribution.
export const PROMPT_VERSION = 'v2.5.0'

// ============================================================================
// 1. Analysis Output (Phase 1 — Claude Haiku)
// ============================================================================

/** Question type enum matching PrescriptionAgentQuestion.type */
export type QuestionType = 'single_choice' | 'multi_choice' | 'text'

/** A clarification question the analysis model wants to ask the trainer */
export interface CompactAnalysisQuestion {
    id: string
    question: string
    context: string
    type: QuestionType
    options?: string[]
    allows_text?: boolean
    placeholder?: string
}

/** The compact output returned by the analysis model */
export interface CompactAnalysisOutput {
    student_summary: string
    identified_gaps: string[]
    questions: CompactAnalysisQuestion[]
}

// ============================================================================
// 2. Generation Output (Phase 2 — GPT-4.1-mini)
// ============================================================================

/**
 * Note keys that the LLM can assign to exercises.
 * The backend translates these into localized PT-BR text.
 * Using enum keys instead of free-text reduces output tokens by ~60%.
 */
export type ExerciseNoteKey =
    | 'compound_anchor'          // Main compound movement anchoring the workout
    | 'replaces_stalled'         // Replaces a stalled exercise from previous program
    | 'favorite_included'        // Included because it's a student favorite
    | 'movement_pattern_cover'   // Covers a required movement pattern
    | 'volume_filler'            // Fills remaining volume budget for the muscle group
    | 'unilateral_balance'       // Unilateral work for balance/stability
    | 'isolation_complement'     // Isolation complement after compounds
    | 'activation_warmup'        // Light activation/warmup exercise
    | 'conditioning_finisher'    // Conditioning or finisher at end of session
    | 'clinical_safe_pick'       // Chosen specifically for safety given medical restrictions
    | 'adherence_simple'         // Simple exercise for low-adherence students
    | 'emphasis_priority'        // Prioritized due to trainer's emphasis request
    | null                       // No specific note

/** A single item in the compact generation output (exercise, warmup, or cardio) */
export interface CompactWorkoutItem {
    /** Item type: 'exercise' (default when absent), 'warmup', or 'cardio' */
    item_type?: 'exercise' | 'warmup' | 'cardio'
    /** UUID from the exercise pool (required for exercises, absent for warmup/cardio) */
    exercise_id?: string
    /** Number of sets (required for exercises) */
    sets?: number
    /** Rep range string, e.g. "8-12" (required for exercises) */
    reps?: string
    /** Rest between sets in seconds (required for exercises) */
    rest_seconds?: number
    /** Functional category within the workout (required for exercises) */
    exercise_function?: ExerciseFunction
    /** 0-2 substitute exercise UUIDs from the pool */
    substitute_exercise_ids?: string[]
    /** Semantic key describing why this exercise was chosen */
    note_key?: ExerciseNoteKey
    /** Configuration for warmup/cardio items */
    item_config?: Record<string, unknown>
}

/** A single workout day in the compact generation output */
export interface CompactWorkout {
    /** Workout display name, e.g. "Upper A" */
    name: string
    /** 0-based order in the program */
    order_index: number
    /** Days of week (0=Sun, 6=Sat) */
    scheduled_days: number[]
    /** Exercises in execution order */
    items: CompactWorkoutItem[]
}

/** The complete compact output returned by the generation model */
export interface CompactGenerationOutput {
    program: {
        /** Short program name, e.g. "PPL+ Hipertrofia" */
        name: string
        /** Duration in weeks (typically 4) */
        duration_weeks: number
    }
    workouts: CompactWorkout[]
    meta: {
        /** Model confidence 0.0-1.0 */
        confidence: number
        /** Max 3 short attention flags for the trainer */
        flags: string[]
    }
}

// ============================================================================
// 3. JSON Schema for OpenAI Structured Output
// ============================================================================

/**
 * JSON Schema used with OpenAI's response_format: { type: "json_schema" }.
 * Must follow OpenAI's strict structured output rules:
 *   - additionalProperties: false at every object level
 *   - all properties listed in "required"
 *   - no unsupported keywords
 *
 * Kept intentionally flat to minimize structured-output failures.
 */
export const GENERATION_JSON_SCHEMA = {
    name: 'prescription_program',
    strict: true,
    schema: {
        type: 'object' as const,
        additionalProperties: false,
        required: ['program', 'workouts', 'meta'],
        properties: {
            program: {
                type: 'object' as const,
                additionalProperties: false,
                required: ['name', 'duration_weeks'],
                properties: {
                    name: { type: 'string' as const },
                    duration_weeks: { type: 'number' as const },
                },
            },
            workouts: {
                type: 'array' as const,
                items: {
                    type: 'object' as const,
                    additionalProperties: false,
                    required: ['name', 'order_index', 'scheduled_days', 'items'],
                    properties: {
                        name: { type: 'string' as const },
                        order_index: { type: 'number' as const },
                        scheduled_days: {
                            type: 'array' as const,
                            items: { type: 'number' as const },
                        },
                        items: {
                            type: 'array' as const,
                            items: {
                                type: 'object' as const,
                                additionalProperties: false,
                                required: [
                                    'item_type',
                                    'exercise_id', 'sets', 'reps', 'rest_seconds',
                                    'exercise_function', 'substitute_exercise_ids', 'note_key',
                                    'item_config',
                                ],
                                properties: {
                                    item_type: {
                                        type: 'string' as const,
                                        enum: ['exercise', 'warmup', 'cardio'],
                                    },
                                    exercise_id: { type: ['string', 'null'] as const },
                                    sets: { type: ['number', 'null'] as const },
                                    reps: { type: ['string', 'null'] as const },
                                    rest_seconds: { type: ['number', 'null'] as const },
                                    exercise_function: {
                                        type: ['string', 'null'] as const,
                                        enum: ['warmup', 'activation', 'main', 'accessory', 'conditioning', null],
                                    },
                                    substitute_exercise_ids: {
                                        type: 'array' as const,
                                        items: { type: 'string' as const },
                                    },
                                    note_key: {
                                        type: ['string', 'null'] as const,
                                        enum: [
                                            'compound_anchor',
                                            'replaces_stalled',
                                            'favorite_included',
                                            'movement_pattern_cover',
                                            'volume_filler',
                                            'isolation_complement',
                                            'unilateral_balance',
                                            'activation_warmup',
                                            'conditioning_finisher',
                                            'clinical_safe_pick',
                                            'adherence_simple',
                                            'emphasis_priority',
                                            null,
                                        ],
                                    },
                                    // OpenAI Structured Outputs strict mode rejects any
                                    // object that lacks properties/required/additionalProperties:false.
                                    // We accept item_config as a JSON string (parsed by
                                    // validateCompactGeneration below) so warmup/cardio
                                    // payloads stay flexible without growing the schema.
                                    item_config: {
                                        type: ['string', 'null'] as const,
                                    },
                                },
                            },
                        },
                    },
                },
            },
            meta: {
                type: 'object' as const,
                additionalProperties: false,
                required: ['confidence', 'flags'],
                properties: {
                    confidence: { type: 'number' as const },
                    flags: {
                        type: 'array' as const,
                        items: { type: 'string' as const },
                    },
                },
            },
        },
    },
} as const

// ============================================================================
// 4. Validation Helpers
// ============================================================================

/**
 * Validates a parsed object against the CompactGenerationOutput structure.
 * Used for Claude responses (which don't enforce schema natively).
 * Returns the validated output or null if invalid.
 */
export function validateCompactGeneration(raw: unknown): CompactGenerationOutput | null {
    if (!raw || typeof raw !== 'object') return null
    const obj = raw as Record<string, unknown>

    // Validate program. Mirrors OpenAI strict mode: reject unknown fields so a
    // Claude response can't smuggle in schema-creep through the fuzzy parser.
    const program = obj.program as Record<string, unknown> | undefined
    if (!program || typeof program.name !== 'string' || typeof program.duration_weeks !== 'number') {
        return null
    }
    for (const key of Object.keys(program)) {
        if (key !== 'name' && key !== 'duration_weeks') return null
    }

    // Validate workouts array
    if (!Array.isArray(obj.workouts) || obj.workouts.length === 0) {
        return null
    }

    const validFunctions = new Set(['warmup', 'activation', 'main', 'accessory', 'conditioning'])

    // Track every item's resolved item_config so the normalization step below
    // can reuse the parsed object without running JSON.parse twice.
    const resolvedItemConfigs: Array<Record<string, unknown> | null> = []

    for (const workout of obj.workouts) {
        if (!workout || typeof workout !== 'object') return null
        const w = workout as Record<string, unknown>
        if (typeof w.name !== 'string') return null
        if (!Array.isArray(w.items) || w.items.length === 0) return null

        for (const item of w.items) {
            if (!item || typeof item !== 'object') return null
            const it = item as Record<string, unknown>
            const itemType = (it.item_type as string) || 'exercise'

            const parsedConfig = parseItemConfig(it.item_config)
            if (parsedConfig === PARSE_ERROR) return null
            resolvedItemConfigs.push(parsedConfig)

            if (itemType === 'warmup' || itemType === 'cardio') {
                // Warmup/cardio: item_config required, exercise fields optional.
                if (!parsedConfig) return null
            } else {
                // Exercise: exercise_id, sets, reps, rest_seconds, exercise_function required
                if (typeof it.exercise_id !== 'string') return null
                if (typeof it.sets !== 'number') return null
                if (typeof it.reps !== 'string') return null
                if (typeof it.rest_seconds !== 'number') return null
                if (!validFunctions.has(it.exercise_function as string)) return null
            }
        }
    }

    // Validate meta
    const meta = obj.meta as Record<string, unknown> | undefined
    if (!meta || typeof meta.confidence !== 'number') return null
    if (!Array.isArray(meta.flags)) return null

    // Normalize. We iterate again but align each item with the pre-parsed
    // item_config captured above so JSON.parse runs exactly once per item.
    let configIndex = 0
    return {
        program: {
            name: program.name as string,
            duration_weeks: program.duration_weeks as number,
        },
        workouts: (obj.workouts as any[]).map((w: any, wi: number) => ({
            name: w.name,
            order_index: typeof w.order_index === 'number' ? w.order_index : wi,
            scheduled_days: Array.isArray(w.scheduled_days) ? w.scheduled_days : [],
            items: (w.items as any[]).map((it: any) => {
                const itemType = it.item_type || 'exercise'
                const parsedConfig = resolvedItemConfigs[configIndex++] ?? null
                if (itemType === 'warmup' || itemType === 'cardio') {
                    return {
                        item_type: itemType,
                        exercise_id: undefined,
                        sets: undefined,
                        reps: undefined,
                        rest_seconds: undefined,
                        exercise_function: undefined,
                        substitute_exercise_ids: [],
                        note_key: null,
                        item_config: parsedConfig ?? {},
                    } as CompactWorkoutItem
                }
                return {
                    item_type: 'exercise',
                    exercise_id: it.exercise_id,
                    sets: it.sets,
                    reps: it.reps,
                    rest_seconds: it.rest_seconds,
                    exercise_function: it.exercise_function,
                    substitute_exercise_ids: Array.isArray(it.substitute_exercise_ids) ? it.substitute_exercise_ids : [],
                    note_key: it.note_key ?? null,
                    item_config: undefined,
                } as CompactWorkoutItem
            }),
        })),
        meta: {
            confidence: Math.max(0, Math.min(1, meta.confidence as number)),
            flags: (meta.flags as any[]).filter((f: unknown) => typeof f === 'string').slice(0, 3),
        },
    }
}

/**
 * Sentinel returned by parseItemConfig on parse failure. Keeps null as a
 * valid "absent" value distinct from "attempted and failed".
 */
const PARSE_ERROR = Symbol('PARSE_ERROR')

/**
 * Accepts the three shapes OpenAI can legally emit for item_config:
 *   - null / undefined → null
 *   - string (new strict-mode shape) → JSON.parse in try/catch
 *   - object (legacy callers like the heuristic builder) → passthrough
 *
 * Returns PARSE_ERROR when a string value is not valid JSON — the caller
 * treats that as a validation failure so it gets logged via
 * `[Smart-v2] abort: invalid_compact reason=item_config is not valid JSON`.
 */
function parseItemConfig(
    raw: unknown,
): Record<string, unknown> | null | typeof PARSE_ERROR {
    if (raw == null) return null
    if (typeof raw === 'string') {
        const trimmed = raw.trim()
        if (trimmed === '' || trimmed === 'null') return null
        try {
            const parsed = JSON.parse(trimmed)
            if (parsed === null) return null
            if (typeof parsed !== 'object' || Array.isArray(parsed)) {
                console.warn('[schemas] item_config is not valid JSON: expected object, got', typeof parsed)
                return PARSE_ERROR
            }
            return parsed as Record<string, unknown>
        } catch (err) {
            const msg = err instanceof Error ? err.message : String(err)
            console.warn(`[schemas] item_config is not valid JSON: ${msg}`)
            return PARSE_ERROR
        }
    }
    if (typeof raw === 'object' && !Array.isArray(raw)) {
        return raw as Record<string, unknown>
    }
    console.warn(`[schemas] item_config has unsupported type: ${typeof raw}`)
    return PARSE_ERROR
}

/**
 * Validates a parsed object against the CompactAnalysisOutput structure.
 * Returns the validated output or null if invalid.
 */
export function validateCompactAnalysis(raw: unknown): CompactAnalysisOutput | null {
    if (!raw || typeof raw !== 'object') return null
    const obj = raw as Record<string, unknown>

    if (typeof obj.student_summary !== 'string') return null
    if (!Array.isArray(obj.identified_gaps)) return null
    if (!Array.isArray(obj.questions)) return null

    const validTypes = new Set(['single_choice', 'multi_choice', 'text'])

    const questions: CompactAnalysisQuestion[] = []
    for (const q of obj.questions) {
        if (!q || typeof q !== 'object') continue
        const qObj = q as Record<string, unknown>
        if (typeof qObj.question !== 'string' || !qObj.question) continue
        if (!validTypes.has(qObj.type as string)) continue

        questions.push({
            id: typeof qObj.id === 'string' ? qObj.id : `q${questions.length + 1}`,
            question: qObj.question as string,
            context: typeof qObj.context === 'string' ? qObj.context as string : '',
            type: qObj.type as QuestionType,
            options: Array.isArray(qObj.options) ? qObj.options as string[] : undefined,
            allows_text: typeof qObj.allows_text === 'boolean' ? qObj.allows_text : undefined,
            placeholder: typeof qObj.placeholder === 'string' ? qObj.placeholder as string : undefined,
        })
    }

    return {
        student_summary: obj.student_summary as string,
        identified_gaps: (obj.identified_gaps as unknown[]).filter((g): g is string => typeof g === 'string'),
        questions,
    }
}
