-- ============================================================================
-- Kinevo — 088 Assistant Insights
-- ============================================================================
-- Phase 1 of the Kinevo Assistant: proactive insights generated by
-- deterministic rules (CRON). Schema is forward-compatible with Phase 2
-- (LLM-generated insights via GPT-4.1-mini through llm-client.ts).
-- ============================================================================

CREATE TABLE assistant_insights (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    trainer_id UUID NOT NULL REFERENCES trainers(id) ON DELETE CASCADE,
    student_id UUID REFERENCES students(id) ON DELETE CASCADE,
    category TEXT NOT NULL CHECK (category IN ('alert', 'progression', 'suggestion', 'summary')),
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('critical', 'high', 'medium', 'low')),
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    action_type TEXT,
    action_metadata JSONB DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'read', 'dismissed', 'acted')),
    insight_key TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'rules' CHECK (source IN ('rules', 'llm')),
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(trainer_id, insight_key)
);

CREATE INDEX idx_assistant_insights_trainer ON assistant_insights(trainer_id, status, created_at DESC);
CREATE INDEX idx_assistant_insights_student ON assistant_insights(student_id);
CREATE INDEX idx_assistant_insights_expires ON assistant_insights(expires_at) WHERE expires_at IS NOT NULL;

-- RLS
ALTER TABLE assistant_insights ENABLE ROW LEVEL SECURITY;

-- Trainers can read and update status of their own insights
CREATE POLICY "Trainer can read own insights" ON assistant_insights
    FOR SELECT USING (trainer_id = current_trainer_id());

CREATE POLICY "Trainer can update own insights" ON assistant_insights
    FOR UPDATE USING (trainer_id = current_trainer_id())
    WITH CHECK (trainer_id = current_trainer_id());

-- Service role (CRON) can do everything
CREATE POLICY "Service role full access" ON assistant_insights
    FOR ALL USING (auth.role() = 'service_role');

-- Enable Realtime replication (same pattern as trainer_notifications)
ALTER PUBLICATION supabase_realtime ADD TABLE assistant_insights;

-- ============================================================================
-- RPC: detect_training_gaps
-- Returns students with active programs who haven't trained in 7+ days.
-- Used by the generate-insights CRON for efficient gap detection.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.detect_training_gaps(p_trainer_id UUID)
RETURNS TABLE(student_id UUID, student_name TEXT, last_completed_at TIMESTAMPTZ, days_since_last INTEGER)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT
        s.id AS student_id,
        s.name AS student_name,
        MAX(ws.completed_at) AS last_completed_at,
        COALESCE(DATE_PART('day', NOW() - MAX(ws.completed_at))::int, 999) AS days_since_last
    FROM students s
    JOIN assigned_programs ap ON ap.student_id = s.id
        AND ap.trainer_id = p_trainer_id
        AND ap.status = 'active'
    LEFT JOIN workout_sessions ws ON ws.student_id = s.id
        AND ws.status = 'completed'
    WHERE s.coach_id = p_trainer_id
        AND s.status = 'active'
        AND s.is_trainer_profile IS NOT TRUE
    GROUP BY s.id, s.name
    HAVING MAX(ws.completed_at) IS NULL
        OR DATE_PART('day', NOW() - MAX(ws.completed_at)) >= 7
$$;
